all:
	gcc negate_image.c -fopenmp -lgd -lpng -lz -ljpeg -lfreetype -lm -o negate_image
negate_image:
	gcc negate_image.c -fopenmp -lgd -lpng -lz -ljpeg -lfreetype -lm -o negate_image
clean:
	rm negate-image